config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django
    path("admin/", admin.site.urls),
    # Third-party apps
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # local apps
    path("mail/", include("project.messaging.urls")),
    path("members/", include("project.members.urls")),
    path("", include("project.pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

project/members/urls.py
from django.urls import path

from .views import MemberDetailView, MyFamilyView

app_name = "members"
urlpatterns = [
    path("my-family/", MyFamilyView.as_view(), name="my-family"),
    path("<slug:slug>/", MemberDetailView.as_view(), name="detail"),
]

project/messaging/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .api import update, delete_attachment
from .views import (
    MessageCreateView,
    MailboxDetailView,
    MailboxDraftsView,
    MailboxArchiveView,
    MailboxTrashView,
    InboxView,
    MailboxSentView,
    MessageDraftView,
)

app_name = "messaging"
urlpatterns = [
    path("", InboxView.as_view(), name="inbox"),
    path("inbox/", RedirectView.as_view(pattern_name="messaging:inbox")),
    path("compose/", MessageCreateView.as_view(), name="create"),
    path("drafts/", MailboxDraftsView.as_view(), name="drafts"),
    path("sent/", MailboxSentView.as_view(), name="sent"),
    path("trash/", MailboxTrashView.as_view(), name="trash"),
    path("archive/", MailboxArchiveView.as_view(), name="archive"),
    path("drafts/<uuid:pk>/", MessageDraftView.as_view(), name="update"),
    path("<uuid:pk>/", MailboxDetailView.as_view(), name="detail"),
    path("api/v1/update/", update, name="api_update"),
    path("api/v1/delete/", delete_attachment, name="api_delete"),
]

project/pages/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .views import AboutPageView, ContactPageView, HomePageView, RegisterPageView
from .views import PageDetailView

app_name = "pages"
urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
    path("home/", RedirectView.as_view(pattern_name="pages:home")),
    path("about/", AboutPageView.as_view(), name="about"),
    path("contact/", ContactPageView.as_view(), name="contact"),
    path("register/", RegisterPageView.as_view(), name="register"),
    path("<slug:slug>/", PageDetailView.as_view(), name="detail"),
]

project/members/models.py
from django.contrib.auth.models import AbstractUser, UserManager
from django.db import models
from django.db.models import Count
from django.urls import reverse_lazy
from django.utils.translation import gettext as _


def get_photo_upload_path(instance, filename):
    return f"members/headshots/{instance.username}/{filename}"


class Family(models.Model):
    class Meta:
        verbose_name = _("family")
        verbose_name_plural = _("families")

    def __str__(self):
        if self.members.exists():
            return _("%(last_names)s Family") % {
                "last_names": "/".join(
                    self.members.values_list("last_name", flat=True)
                    .annotate(count=Count("last_name"))
                    .filter(count=1)
                )
            }

        else:
            return _("Empty Family")

    def get_adults(self):
        return self.members.filter(role__in=[Member.Role.PARENT, Member.Role.GUARDIAN])

    def get_children(self):
        return self.members.filter(role=Member.Role.SCOUT)


class MemberManager(UserManager):
    def create_user(
        self, username, first_name, last_name, email=None, password=None, **extra_fields
    ):
        return super().create_user(
            username,
            email,
            password,
            first_name=first_name,
            last_name=last_name,
            **extra_fields,
        )

    def create_superuser(
        self, username, first_name, last_name, email=None, password=None, **extra_fields
    ):
        return super().create_superuser(
            username,
            email,
            password,
            first_name=first_name,
            last_name=last_name,
            **extra_fields,
        )


class Member(AbstractUser):
    class Gender(models.TextChoices):
        MALE = "M", _("Boy")
        FEMALE = "F", _("Girl")
        NON_BINARY = "NB", _("Non-binary")
        OTHER = "O", _("Prefer not to say")

    class Role(models.TextChoices):
        SCOUT = "S", _("Child")
        PARENT = "P", _("Parent")
        GUARDIAN = "G", _("Guardian")
        OTHER = "E", _("Extended Family")
        FRIEND = "F", _("Friend of the Family")

    first_name = models.CharField(_("first name"), max_length=150)
    middle_name = models.CharField(_("middle_name"), max_length=150, blank=True)
    last_name = models.CharField(_("last name"), max_length=150)
    nickname = models.CharField(_("nickname"), max_length=150, blank=True)

    gender = models.CharField(_("gender"), max_length=2, choices=Gender.choices)
    family = models.ForeignKey(
        Family,
        on_delete=models.PROTECT,
        related_name="members",
        related_query_name="families",
        blank=True,
        null=True,
    )
    photo = models.ImageField(
        _("photo"),
        upload_to=get_photo_upload_path,
        default="img/generic.png",
        help_text=_(
            "We use profile photos in the Pack Directory to help members match "
            "names with faces. A good photo is taken from the shoulders up and "
            "with the face clearly visible. Photos are available only for Pack "
            "members and are not shared."
        ),
    )

    objects = MemberManager()

    REQUIRED_FIELDS = ["first_name", "last_name", "gender", "email"]

    class Meta:
        verbose_name = _("Member")
        verbose_name_plural = _("Members")

    def __str__(self):
        return self.get_full_name()

    def get_absolute_url(self):
        return reverse_lazy("members:detail", kwargs={"slug": self.username})

    def get_full_name(self):
        """
        Return the preferred name plus the last name with a space between
        """
        return f"{self.get_short_name()} {self.last_name}"

    def get_short_name(self):
        """
        Return either the nickname or first_name for the member.
        """
        return self.nickname or self.first_name

project/addresses/forms.py
from django import forms

from .models import Address, Email, Phone


class AddressForm(forms.ModelForm):
    class Meta:
        model = Address
        fields = (
            "type",
            "street",
            "street2",
            "city",
            "state",
            "zip_code",
            "is_published",
        )


class EmailForm(forms.ModelForm):
    class Meta:
        model = Email
        fields = ("type", "address", "is_published", "is_subscribed")


class PhoneForm(forms.ModelForm):
    class Meta:
        model = Phone
        fields = ("type", "number", "is_published")

project/members/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm

from .models import Member


class MemberChangeForm(UserChangeForm):
    class Meta(UserChangeForm.Meta):
        model = Member


class MemberCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Member
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "middle_name",
            "last_name",
            "nickname",
            "gender",
        )

project/messaging/forms.py
from django import forms

from .models import Message


class AttachmentForm(forms.Form):
    attachments = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True, "class": "custom-file-input"}))  # attrs={"class": "custom-file-input"}


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("subject", "body", "parent")
        widgets = {
            "subject": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.HiddenInput(),
            "parent": forms.HiddenInput()
        }

project/addresses/views.py
from django.shortcuts import render

# Create your views here.

project/members/views.py
from django.views.generic import DetailView

from .models import Member


class MemberDetailView(DetailView):
    model = Member
    slug_field = "username"


class MyFamilyView(MemberDetailView):
    def get_object(self, queryset=None):
        return self.get_queryset().get(id=self.request.user.id)

project/messaging/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import AttachmentForm, MessageForm
from .mixins import MessageIsForUserTest
from .models import Attachment, Mailbox, Message


class MailboxView(LoginRequiredMixin, ListView):
    model = Mailbox
    context_object_name = "mailbox_items"
    template_name = "messaging/message_list.html"

    def get_queryset(self):
        return super().get_queryset().select_related("message").filter(member=self.request.user)


class InboxView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.INBOX)


class MailboxArchiveView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.ARCHIVE)


class MailboxTrashView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.TRASH)


class MailboxDraftsView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = "drafts"
    template_name = "messaging/drafts.html"

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user, date_sent__isnull=True)


class MailboxSentView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = "sent_items"
    template_name = "messaging/sent_items.html"

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user, date_sent__isnull=False)


class MailboxDetailView(MessageIsForUserTest, DetailView):
    model = Message
    context_object_name = "message"
    template_name = "messaging/message_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = MessageForm
        context["status"] = Mailbox.objects.filter(message=self.object, member=self.request.user).first()
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.receipts.filter(member=self.request.user).exists():
            obj.receipts.get(member=self.request.user).mark_read()
        return obj


class MessageCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Message
    template_name = "messaging/message_form.html"
    form_class = MessageForm
    success_message = _("Your message: <strong>%(subject)s</strong>, was %(action)s successfully.")

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        attachment_form = context["attachment_form"]
        files = self.request.FILES.getlist('attachments')
        if attachment_form.is_valid():
            message = form.save()
            message.author = self.request.user
            for file in files:
                Attachment.objects.create(message=message, file=file)
            return super().form_valid(form)
        else:
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["attachment_form"] = AttachmentForm(self.request.POST, self.request.FILES)
        else:
            context["attachment_form"] = AttachmentForm()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            action=_("sent") if self.object.date_sent else _("saved")
        )

    def get_success_url(self):
        if 'draft' in self.request.POST:
            return reverse_lazy("messaging:update", kwargs={"pk": self.object.uuid})

        self.object.send()
        return reverse_lazy("messaging:detail", kwargs={"pk": self.object.uuid})


class MessageDraftView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Message
    template_name = "messaging/message_form.html"
    form_class = MessageForm
    success_message = _("Your message: <strong>%(subject)s</strong>, was %(action)s successfully.")

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        attachment_form = context["attachment_form"]
        files = self.request.FILES.getlist('attachments')
        if attachment_form.is_valid():
            message = form.save(commit=False)
            for file in files:
                Attachment.objects.create(message=message, file=file)
            return super().form_valid(form)
        else:
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["attachment_form"] = AttachmentForm(self.request.POST, self.request.FILES)
        else:
            context["attachment_form"] = AttachmentForm()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            action=_("sent") if self.object.date_sent else _("saved")
        )

    def get_success_url(self):
        if 'draft' in self.request.POST:
            return reverse_lazy("messaging:update", kwargs={"pk": self.object.uuid})

        self.object.send()
        return reverse_lazy("messaging:detail", kwargs={"pk": self.object.uuid})

project/pages/views.py
from django.contrib import messages
from django.core.exceptions import PermissionDenied
from django.http import Http404
from django.urls import reverse
from django.utils.translation import gettext as _
from django.views.generic import DetailView

from .models import Page


class PageDetailView(DetailView):
    model = Page
    template_name = "pages/page_detail.html"

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.content_blocks.exists():
            return obj
        else:
            raise PermissionDenied

    def get_queryset(self):
        return super().get_queryset().with_content_blocks(user=self.request.user)


class HomePageView(PageDetailView):
    template_name = "pages/home.html"

    def get_object(self, **kwargs):
        if self.request.user.is_authenticated and (
            (
                not self.request.user.family
                or self.request.user.family.members.count() == 1
            )
        ):
            messages.add_message(
                self.request,
                messages.INFO,
                _(
                    "WOW, Such empty! Go visit your <a class='alert-link' href='%(url)s'>My Family</a> "
                    "page to add some family members."
                ) % {"url": reverse("members:my-family")},
            )
        try:
            return self.get_queryset().get(base=Page.Base.HOME)
        except Page.DoesNotExist:
            raise Http404(
                _(
                    "The home page was requested but has not yet been created in the database"
                )
            )


class AboutPageView(PageDetailView):
    template_name = "pages/about.html"

    def get_object(self, **kwargs):
        try:
            return self.get_queryset().get(base=Page.Base.ABOUT)
        except Page.DoesNotExist:
            raise Http404(
                _(
                    "An about us page was requested but has not yet been created in the database"
                )
            )


class ContactPageView(PageDetailView):
    template_name = "pages/contact.html"

    def get_object(self, **kwargs):
        try:
            return self.get_queryset().get(base=Page.Base.CONTACT)
        except Page.DoesNotExist:
            raise Http404(
                _(
                    "A contact page was requested but has not yet been created in the database"
                )
            )


class RegisterPageView(PageDetailView):
    template_name = "pages/register.html"

    def get_object(self, **kwargs):
        try:
            return self.get_queryset().get(base=Page.Base.REGISTER)
        except Page.DoesNotExist:
            raise Http404(
                _(
                    "A registration page was requested but has not yet been created in the database"
                )
            )

project/templates/base.html
{% load static %}
<!doctype html>
<html lang="en-US">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{% block title %}Hello, World{% endblock %}</title>
    <meta name="color-scheme" content="light dark">
    <!--  Begin CSS  --------------------------------------------------------->
    {% block css %}
      <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-dark-4@0.0.9/dist/bootstrap-dark.min.css" integrity="sha256-45MEZkAkRGg+ZUL+iUP0LFI0+wrL4Ru6n0XEXs5wIHo=" crossorigin="anonymous">
      <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}
    <!--  End CSS  ----------------------------------------------------------->
  </head>

  <body>
    {% block navbar %}
      <!--  Begin NavBar  ---------------------------------------------------->
      {% include 'navbar.html' %}
      <!--  End NavBar  ------------------------------------------------------>
    {% endblock %}

    {% if messages %}
      <!--  Alerts Section  -------------------------------------------------->
      {% for message in messages %}
        <div class="alert alert-dismissible{% if message.tags %} alert-{{ message.tags }}{% endif %} text-center fade show rounded-0" role="alert">
          {{ message|safe }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="fas fa-times-circle"></i>
          </button>
        </div>
      {% endfor %}
      <!--  End alerts  ------------------------------------------------------>
    {% endif %}

    <!--  Main Content  ------------------------------------------------------>
    <main class="container my-5">
      {% block content %}{% endblock %}
    </main>
    <!--  End main content  -------------------------------------------------->

    <!--  Begin JavaScript  -------------------------------------------------->
    {% block js %}
      <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha256-4+XzXVhsDmqanXGHaHvgh1gMQKX40OUvDEBTu8JcmNs=" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-Piv4xVNRyMGpqkS2by6br4gNJ7DXjqk09RmUpJ8jgGtD7zP9yug3goQfGII0yAns" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.2/js/all.min.js" integrity="sha256-5FoddZC9pssK9Wo0fpeSFbiFSsSdVLcJHvHmTRqleKY=" crossorigin="anonymous"></script>
    {% endblock js %}
    <!--  End JavaScript  ---------------------------------------------------->
  </body>
</html>

project/templates/navbar.html
{% load navbar %}

{% block navbar %}
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-links" aria-controls="navbar-links" aria-expanded="false" aria-label="toggle navigation"></button>
    <div class="collapse navbar-collapse" id="navbar-links">
      <ul class="navbar-nav">
        <!--  Standard pages  ------------------------------------------------>
        {% url 'pages:home' as home_page %}
        <li class="nav-item{% if request.path == home_page %} active{% endif %}">
          <a class="nav-link" href="{{ home_page }}">Home</a>
        </li>
        {% url 'pages:contact' as contact_page %}
        <li class="nav-item{% if request.path == contact_page %} active{% endif %}">
          <a class="nav-link" href="{{ contact_page }}">Contact</a>
        </li>
        {% url 'pages:about' as about_page %}
        <li class="nav-item{% if request.path == about_page %} active{% endif %}">
          <a class="nav-link" href="{{ about_page }}">About Us</a>
        </li>

        <!--  Dynamic links  ------------------------------------------------->
        {% get_nav_links as nav_links %}
        {% for link in nav_links %}
          <li class="nav-item{% if request.path == link.get_absolute_url %} active{% endif %}">
            <a class="nav-link" href="{{ link.get_absolute_url }}">{{ link.title }}</a>
          </li>
        {% endfor %}

        <!--  Mailbox  ------------------------------------------------------->
        <ul class="navbar-nav ml-auto">
          {% if user.is_authenticated %}
            <li class="nav-item{% if request.resolver_match.app_name == 'messaging' %} active{% endif %}">
              <a class="nav-link" href="{% url "messaging:inbox" %}">
                <i class="fas fa-envelope fa-lg"></i>
                <span class="badge badge-pill badge-danger unread-messages-counter{% if not user.mailbox.unread %} d-none{% endif %}">{{ user.mailbox.unread }}</span>
              </a>
            </li>
          {% endif %}
        </ul>

      </ul>
    </div>
  </nav>
{% endblock %}