config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # Django
    path("admin/", admin.site.urls),
    # Third-party apps
    path('ckeditor/', include('ckeditor_uploader.urls')),
    # local apps
    path("mail/", include("project.messaging.urls")),
    path("members/", include("project.members.urls")),
    path("", include("project.pages.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path("__debug__/", include(debug_toolbar.urls)),
    ] + urlpatterns

project/messaging/urls.py
from django.urls import path
from django.views.generic import RedirectView

from .api import update, delete_attachment
from .views import (
    MessageCreateView,
    MailboxDetailView,
    MailboxDraftsView,
    MailboxArchiveView,
    MailboxTrashView,
    InboxView,
    MailboxSentView,
    MessageDraftView,
)

app_name = "messaging"
urlpatterns = [
    path("", InboxView.as_view(), name="inbox"),
    path("inbox/", RedirectView.as_view(pattern_name="messaging:inbox")),
    path("compose/", MessageCreateView.as_view(), name="create"),
    path("drafts/", MailboxDraftsView.as_view(), name="drafts"),
    path("sent/", MailboxSentView.as_view(), name="sent"),
    path("trash/", MailboxTrashView.as_view(), name="trash"),
    path("archive/", MailboxArchiveView.as_view(), name="archive"),
    path("drafts/<uuid:pk>/", MessageDraftView.as_view(), name="update"),
    path("<uuid:pk>/", MailboxDetailView.as_view(), name="detail"),
    path("api/v1/update/", update, name="api_update"),
    path("api/v1/delete/", delete_attachment, name="api_delete"),
]

project/messaging/models.py
import uuid

from django.contrib.auth import get_user_model
from django.db import models
from django.db.models import Count, Q, Subquery, OuterRef
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext as _

from pathlib import Path

User = get_user_model()


class Thread(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = _("thread")
        verbose_name_plural = _("threads")

    def __str__(self):
        return str(self.uuid)


class MessageQuerySet(models.QuerySet):
    def with_receipts(self, user):
        receipts = Mailbox.objects.filter(message=OuterRef('uuid'), member=user)
        return self.annotate(date_read=Subquery(receipts.values('date_read')))

    def prefetch_receipts(self, user):
        return self.prefetch_related(
            models.Prefetch("receipts", queryset=Mailbox.objects.filter(member=user))
        )


class Message(models.Model):
    uuid = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    author = models.ForeignKey(
        User, on_delete=models.SET_NULL, related_name="messages_sent", null=True
    )
    subject = models.CharField(
        _("subject"), max_length=998, help_text=_("The message subject")
    )
    body = models.TextField(_("body"), help_text=_("What do you want to say?"))
    recipients = models.ManyToManyField(
        User, related_name="messages", through="messaging.Mailbox", blank=True
    )

    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    date_sent = models.DateTimeField(blank=True, null=True)
    thread = models.ForeignKey(
        Thread, on_delete=models.CASCADE, related_name="messages", blank=True
    )
    parent = models.ForeignKey(
        "self", on_delete=models.CASCADE, related_name="replies", blank=True, null=True
    )

    objects = MessageQuerySet().as_manager()

    class Meta:
        get_latest_by = "date_modified"
        ordering = ["-date_modified"]
        verbose_name = _("message")
        verbose_name_plural = _("messages")

    def __str__(self):
        return _("On %(date)s at %(time)s, %(author)s wrote: %(subject)s") % {
            "date": self.date_modified.strftime("%B %-d, %Y"),
            "time": self.date_modified.strftime("%-I:%M %p %Z"),
            "author": self.author,
            "subject": self.subject,
        }

    def get_absolute_url(self):
        return reverse_lazy("messaging:detail", kwargs={"pk": self.uuid})

    def clean(self):
        if not self.thread_id:
            self.assign_thread()
        super().clean()

    def assign_thread(self):
        self.thread = self.parent.thread if self.parent else Thread.objects.create()

    def send(self):
        # TODO: implement sending the message
        self.date_sent = timezone.now()
        self.save()

    @property
    def status(self):
        """Should be accessed through a pre_fetched queryset"""
        return self.receipts.first()


def get_attachment_path(instance, filename):
    return f"messages/{instance.message.uuid}/{filename}"


class Attachment(models.Model):
    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="attachments")
    file = models.FileField(_("file"), upload_to=get_attachment_path)

    class Meta:
        verbose_name = _("attachment")
        verbose_name_plural = _("attachments")

    def __str__(self):
        return Path(self.file.name).name


class MailboxQuerySet(models.QuerySet):
    def unread(self):
        return self.aggregate(count=Count("message", filter=Q(date_read__isnull=True, folder=Mailbox.Folder.INBOX)))

    def mark_read(self):
        self.update(date_read=timezone.now())

    def mark_unread(self):
        self.update(date_read=None)


class MailboxManager(models.Manager):
    def get_queryset(self):
        return MailboxQuerySet(self.model, using=self._db)

    def mark_read(self):
        return self.get_queryset().mark_read()

    def mark_unread(self):
        return self.get_queryset().mark_unread()

    def unread(self):
        return self.get_queryset().unread()["count"]


class Mailbox(models.Model):

    class Folder(models.IntegerChoices):
        INBOX = 1, _("Inbox")
        ARCHIVE = 2, _("Archive")
        TRASH = 3, _("Trash")

    message = models.ForeignKey(Message, on_delete=models.CASCADE, related_name="receipts")
    member = models.ForeignKey(User, on_delete=models.CASCADE, related_name="mailbox")
    folder = models.IntegerField(_("folder"), choices=Folder.choices, default=Folder.INBOX)

    date_received = models.DateTimeField(_("received"), auto_now_add=True)
    date_read = models.DateTimeField(_("read"), blank=True, null=True)

    objects = MailboxManager()

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=["message", "member"], name="unique_receipt_per_member"
            )
        ]
        verbose_name = _("mailbox")
        verbose_name_plural = _("mailboxes")

    def __str__(self):
        return self.member.__str__()

    @property
    def read(self):
        return bool(self.date_read)

    def mark_read(self):
        if not self.date_read:
            self.date_read = timezone.now()
            self.save()

    def mark_unread(self):
        self.date_read = None
        self.save()

project/messaging/forms.py
from django import forms

from .models import Message


class AttachmentForm(forms.Form):
    attachments = forms.FileField(required=False, widget=forms.ClearableFileInput(attrs={'multiple': True, "class": "custom-file-input"}))  # attrs={"class": "custom-file-input"}


class MessageForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ("subject", "body", "parent")
        widgets = {
            "subject": forms.TextInput(attrs={"class": "form-control"}),
            "body": forms.HiddenInput(),
            "parent": forms.HiddenInput()
        }

project/messaging/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.utils.translation import gettext as _
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import AttachmentForm, MessageForm
from .mixins import MessageIsForUserTest
from .models import Attachment, Mailbox, Message


class MailboxView(LoginRequiredMixin, ListView):
    model = Mailbox
    context_object_name = "mailbox_items"
    template_name = "messaging/message_list.html"

    def get_queryset(self):
        return super().get_queryset().select_related("message").filter(member=self.request.user)


class InboxView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.INBOX)


class MailboxArchiveView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.ARCHIVE)


class MailboxTrashView(MailboxView):

    def get_queryset(self):
        return super().get_queryset().filter(folder=Mailbox.Folder.TRASH)


class MailboxDraftsView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = "drafts"
    template_name = "messaging/drafts.html"

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user, date_sent__isnull=True)


class MailboxSentView(LoginRequiredMixin, ListView):
    model = Message
    context_object_name = "sent_items"
    template_name = "messaging/sent_items.html"

    def get_queryset(self):
        return super().get_queryset().filter(author=self.request.user, date_sent__isnull=False)


class MailboxDetailView(MessageIsForUserTest, DetailView):
    model = Message
    context_object_name = "message"
    template_name = "messaging/message_detail.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["form"] = MessageForm
        context["status"] = Mailbox.objects.filter(message=self.object, member=self.request.user).first()
        return context

    def get_object(self, queryset=None):
        obj = super().get_object(queryset)
        if obj.receipts.filter(member=self.request.user).exists():
            obj.receipts.get(member=self.request.user).mark_read()
        return obj


class MessageCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = Message
    template_name = "messaging/message_form.html"
    form_class = MessageForm
    success_message = _("Your message: <strong>%(subject)s</strong>, was %(action)s successfully.")

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        attachment_form = context["attachment_form"]
        files = self.request.FILES.getlist('attachments')
        if attachment_form.is_valid():
            message = form.save()
            message.author = self.request.user
            for file in files:
                Attachment.objects.create(message=message, file=file)
            return super().form_valid(form)
        else:
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["attachment_form"] = AttachmentForm(self.request.POST, self.request.FILES)
        else:
            context["attachment_form"] = AttachmentForm()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            action=_("sent") if self.object.date_sent else _("saved")
        )

    def get_success_url(self):
        if 'draft' in self.request.POST:
            return reverse_lazy("messaging:update", kwargs={"pk": self.object.uuid})

        self.object.send()
        return reverse_lazy("messaging:detail", kwargs={"pk": self.object.uuid})


class MessageDraftView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = Message
    template_name = "messaging/message_form.html"
    form_class = MessageForm
    success_message = _("Your message: <strong>%(subject)s</strong>, was %(action)s successfully.")

    def form_valid(self, form):
        context = self.get_context_data(form=form)
        attachment_form = context["attachment_form"]
        files = self.request.FILES.getlist('attachments')
        if attachment_form.is_valid():
            message = form.save(commit=False)
            for file in files:
                Attachment.objects.create(message=message, file=file)
            return super().form_valid(form)
        else:
            return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["attachment_form"] = AttachmentForm(self.request.POST, self.request.FILES)
        else:
            context["attachment_form"] = AttachmentForm()
        return context

    def get_success_message(self, cleaned_data):
        return self.success_message % dict(
            cleaned_data,
            action=_("sent") if self.object.date_sent else _("saved")
        )

    def get_success_url(self):
        if 'draft' in self.request.POST:
            return reverse_lazy("messaging:update", kwargs={"pk": self.object.uuid})

        self.object.send()
        return reverse_lazy("messaging:detail", kwargs={"pk": self.object.uuid})

project/messaging/templates/messaging/drafts.html
{% extends "messaging/mailbox_base.htm" %}

{% load humanize %}

{% block title %}{{ block.super }}: Inbox{% endblock %}

{% block message_content %}
  <div class="list-group list-group-flush mt-3">
    <div class="list-group-item list-group-item-dark">
      <div class="row" id="message-list-header">
        <div class="col-3"><strong>To</strong></div>
        <div class="col"><strong>Subject</strong></div>
        <div class="col-3"><strong>Modified</strong></div>
      </div>
    </div>
    {% for draft in drafts.all %}
      <div class="list-group-item list-group-item-action">
        <a href="{% url 'messaging:update' draft.pk %}" class="row text-decoration-none">
          <div class="col-3">{{ draft.author }}</div>
          <div class="col">{{ draft.subject }}</div>
          <div class="col-3"><span data-toggle="tooltip" title="{{ draft.date_modified }}">{{ draft.date_modified|naturaltime }}</span>{% if draft.attachments.exists %} <i class="fas fa-paperclip float-right"></i>{% endif %}</div>
        </a>
      </div>
    {% empty %}
      <div class="list-group-item text-center p-5">No Messages to Display</div>
    {% endfor %}
  </div>
{% endblock %}

project/messaging/templates/messaging/mailbox_base.htm
{% extends 'base.html' %}

{% load static %}

{% block content %}
    <div class="card mailbox">
        <div class="card-body">
            <div class="row">
                <aside class="col-lg-2" id="sidebar">
                    <div class="text-center mb-3" id="sidebar-header">
                        <i class="fas fa-envelope fa-fw fa-8x text-black-50"></i>
                        <a class="btn btn-sm btn-outline-secondary" href="{% url 'messaging:create' %}">
                            <i class="fas fa-edit"></i> New message
                        </a>
                    </div>
                    <hr>
                    <nav class="nav nav-pills flex-column">
                        <li class="nav-item">
                            <a class="nav-link{% if request.resolver_match.url_name == 'inbox' %} active{% endif %}"
                               href="{% url 'messaging:inbox' %}">
                                <i class="fas fa-inbox fa-fw"></i> Inbox
                                <span class="badge badge-light float-right unread-messages-counter{% if not user.mailbox.unread %} d-none{% endif %}">{{ user.mailbox.unread }}</span>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if request.resolver_match.url_name == 'drafts' %} active{% endif %}"
                               href="{% url 'messaging:drafts' %}">
                                <i class="fas fa-file-alt fa-fw"></i> Drafts
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if request.resolver_match.url_name == 'sent' %} active{% endif %}"
                               href="{% url 'messaging:sent' %}">
                                <i class="fas fa-paper-plane fa-fw"></i> Sent
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if request.resolver_match.url_name == 'trash' %} active{% endif %}"
                               href="{% url 'messaging:trash' %}">
                                <i class="fas fa-trash-alt fa-fw"></i> Trash
                            </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link{% if request.resolver_match.url_name == 'archive' %} active{% endif %}"
                               href="{% url 'messaging:archive' %}">
                                <i class="fas fa-archive fa-fw"></i> Archive
                            </a>
                        </li>

                    </nav>
                </aside>
                <div class="col-lg-10" id="document-window">
                    {% block message_content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </div>
{% endblock content %}


{% block js %}
    {{ block.super }}
    <script>
        const update_url = "{% url 'messaging:api_update' %}"
        const delete_url = "{% url 'messaging:api_delete' %}"
        const csrf_token = "{{ csrf_token }}"

        // Enable Bootstrap tooltips
        $(function () {
            $('[data-toggle="tooltip"]').tooltip()
        })
    </script>
    <script src="{% static 'js/mailbox.js' %}"></script>
{% endblock %}

project/messaging/templates/messaging/message_detail.html
{% extends "messaging/mailbox_base.htm" %}

{% load humanize %}

{% block title %}{{ block.super }}: {{ message.subject }}{% endblock %}

{% block message_content %}
  <div class="list-group-item mb-3">
    <div class="btn-toolbar mb-3 justify-content-center" role="toolbar" aria-label="Message actions toolbar">
      <div class="btn-group btn-group-sm mr-3" role="group" arial-label="Archive or delete">
        <button type="button" class="btn btn-outline-secondary move-btn{% if status.folder == status.Folder.ARCHIVE %} active{% endif %}" data-action="{% if status.folder == status.Folder.ARCHIVE %}unarchive{% else %}archive{% endif %}" data-message="{{ message.pk }}" data-toggle="tooltip" title="Archive this message">
          <i class="fas fa-archive"></i>
        </button>
        <button type="button" class="btn btn-outline-secondary move-btn{% if status.folder == status.Folder.TRASH %} active{% endif %}" data-action="{% if status.folder == status.Folder.TRASH %}recover{% else %}delete{% endif %}" data-message="{{ message.pk }}" data-toggle="tooltip" title="Move this message to Trash">
          <i class="fas fa-trash-alt"></i>
        </button>
      </div>
      <div class="btn-group btn-group-sm" role="group" aria-label="reply or forward">
        <button class="btn btn-outline-secondary btn-reply toolbar-button"
                type="button"
                data-toggle="collapse"
                data-target="#reply-form{% if forloop %}-{{ forloop.parentloop.counter }}{{ forloop.counter }}{% endif %}"
                aria-controls="reply-form{% if forloop %}-{{ forloop.parentloop.counter }}{{ forloop.counter }}{% endif %}"
                aria-expanded="false" title="Reply to the author">
          <i class="fas fa-reply"></i>
        </button>
        <a class="btn btn-outline-secondary toolbar-button" href="#" data-toggle="tooltip" title="Reply to all"><i class="fas fa-reply-all"></i></a>
        <a class="btn btn-outline-secondary toolbar-button" href="#" data-toggle="tooltip" title="Forward"><i class="fas fa-share"></i></a>
      </div>
    </div>

    <div class="row message-wrapper">
      <div class="col-md-2 text-center">
        <a href="{{ message.author.get_absolute_url }}">
          <img src="{{ message.author.photo.url }}" class="img-block rounded-circle" height="80" width="80">
          {{ message.author }}
        </a>
      </div>
      <div class="col-md">
        <div class="row">
          <div class="col"><h3>{{ message.subject }}</h3></div>
          <div class="col-3 text-right">
            <small class="text-muted ">{{ status.date_received|naturaltime }}</small>
            <span class="read-toggler{% if status.date_read %} d-none{% endif %}" data-action="read" data-message="{{ message.pk }}" data-toggle="tooltip" title="Mark as read">
              <i class="fas fa-circle text-primary"></i>
            </span>
            <span class="read-toggler{% if not status.date_read %} d-none{% endif %}" data-action="unread" data-message="{{ message.pk }}" data-toggle="tooltip" title="Mark as unread">
              <i class="far fa-circle text-primary"></i>
            </span>
          </div>
        </div>
        <div>{{ message.body|linebreaks }}</div>
        {% if message.attachments.exists %}
          <ul class="fa-ul">
            {% for attachment in message.attachments.all %}
              <li class="d-inline-block mr-5" id="attachment-{{ attachment.pk }}">
                <span class="fa-li"><i class="far fa-file"></i></span>
                <a href="{{ attachment.file.url }}" target="_blank">{{ attachment }}</a>
              </li>
            {% endfor %}
          </ul>
          <small class="text-muted">
            <span id="attachment-counter">{{ message.attachments.count }}</span> attachment{{ message.attachments.count|pluralize }}
          </small>

        {% endif %}
      </div>
    </div>
    {% include "messaging/snippets/reply.html" %}
  </div>
{% endblock %}

{% block js %}
  {{ block.super }}
  <script>
    $(function () {
      // initialize tooltips on all reply buttons
      $('.btn-reply').tooltip().click(function () {
      })
    })
    $('.btn-reply').on('click', function () {
      // hide all other reply fields when another button is clicked
      $('.collapse').collapse('hide');
      $(".btn-reply").removeClass("active")
      // toggle the active state of the button
      $(this).addClass("active");
    })
  </script>
{% endblock %}

project/messaging/templates/messaging/message_form.html
{% extends "messaging/mailbox_base.htm" %}

{% block title %}{{ block.super }}: New Message{% endblock %}

{% block css %}
  {{ block.super }}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/trix@1.3.1/dist/trix.css" integrity="sha256-EpZ4gghpiHtNH8WufydxT5I9pJeFTRKKti78cuEjBwY=" crossorigin="anonymous">
{% endblock css %}

{% block message_content %}
  <form method="post" action="" enctype="multipart/form-data">
    <div class="form-group" id="subject">
      <label for="{{ form.subject.id_for_label }}">{{ form.subject.label }}</label>
      {{ form.subject }}
      {% if form.subject.help_text %}
        <small id="{{ form.subject.id_for_label }}_help" class="form-text text-muted">{{ form.subject.help_text }}</small>
      {% endif %}
      {% if form.subject.errors %}
        <ul class="invalid-feedback list-unstyled" id="{{ form.subject.id_for_label }}_errors">
          {% for error in form.subject.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>

    <div class="form-group" id="body">
      <label for="{{ form.body.id_for_label }}">{{ form.body.label }}</label>
      {{ form.body }}
      <trix-editor input="{{ form.body.id_for_label }}"></trix-editor>
      {% if form.body.help_text %}
        <small id="{{ form.body.id_for_label }}_help" class="form-text text-muted">{{ form.body.help_text }}</small>
      {% endif %}
      {% if form.body.errors %}
        <ul class="invalid-feedback list-unstyled" id="{{ form.body.id_for_label }}_errors">
          {% for error in form.body.errors %}
            <li>{{ error }}</li>
          {% endfor %}
        </ul>
      {% endif %}
    </div>

    <div class="form-group" id="attachments">
      <div class="custom-file form-row">
        <div class="col-6">
          <label class="custom-file-label" for="{{ attachment_form.attachments.id_for_label }}">{{ attachment_form.attachments.label }}</label>
          {{ attachment_form.attachments }}
          {% if attachment_form.attachments.help_text %}
            <small id="{{ attachment_form.attachments.id_for_label }}_help" class="form-text text-muted">{{ attachment_form.attachments.help_text }}</small>
          {% endif %}
          {% if attachment_form.attachments.errors %}
            <ul class="invalid-feedback list-unstyled" id="{{ attachment_form.attachments.id_for_label }}_errors">
              {% for error in attachment_form.attachments.errors %}
                <li>{{ error }}</li>
              {% endfor %}
            </ul>
          {% endif %}
        </div>
      </div>

      {% if message.attachments.exists %}
        <div class="mt-3">
          <small class="text-muted">
            <span id="attachment-counter">{{ message.attachments.count }}</span> attachment{{ message.attachments.count|pluralize }}
          </small>
          <ul class="list-unstyled">
            {% for attachment in message.attachments.all %}
              <li class="d-inline-block mr-3" id="attachment-{{ attachment.pk }}">
                <span class="badge badge-pill badge-light pl-2">
                  <i class="far fa-file"></i>
                  <a href="{{ attachment.file.url }}" target="_blank">{{ attachment }}</a>
                  <span class="delete-attachment text-muted" data-action="delete" data-attachment="{{ attachment.pk }}" data-toggle="tooltip" title="remove this attachment">
                    <i class="fas fa-times-circle fa-xs"></i>
                  </span>
                </span>
              </li>
            {% endfor %}
          </ul>
        </div>
      {% endif %}
    </div>
    <input type="hidden" name="parent" id="id_parent">
    {% csrf_token %}
    <button class="btn btn-primary" type="submit">Send</button>
    <button class="btn btn-outline-primary" type="submit" name="draft">Save Draft</button>
  </form>
{% endblock %}


{% block js %}
  {{ block.super }}
  {{ form.media }}
  <script src="https://cdn.jsdelivr.net/npm/trix@1.3.1/dist/trix.js" integrity="sha256-RzBtzThsyMXAfHuq7pgmDSDS2XTsUDHQDL3vnGi1Wyk=" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bs-custom-file-input@1.3.4/dist/bs-custom-file-input.min.js" integrity="sha256-e0DUqNhsFAzOlhrWXnMOQwRoqrCRlofpWgyhnrIIaPo=" crossorigin="anonymous"></script>
  <script>
    bsCustomFileInput.init()
  </script>
{% endblock js %}

project/messaging/templates/messaging/message_list.html
{% extends "messaging/mailbox_base.htm" %}

{% load humanize %}

{% block title %}{{ block.super }}: Inbox{% endblock %}

{% block message_content %}
  <div class="list-group list-group-flush mt-3">
    <div class="list-group-item list-group-item-dark">
      <div class="row" id="sent-items-header">
        <div class="col-1"></div>
        <div class="col-3"><strong>To</strong></div>
        <div class="col"><strong>Subject</strong></div>
        <div class="col-3"><strong>Sent</strong></div>
      </div>
    </div>
    {% for entry in mailbox_items.all %}
      <div class="list-group-item list-group-item-action">
        <div class="row">
          <div class="col-1 text-center read-toggler{% if entry.read %} d-none{% endif %}" data-action="read" data-message="{{ entry.message.pk }}" data-toggle="tooltip" title="Mark as read">
            <i class="fas fa-circle text-primary"></i>
          </div>
          <div class="col-1 text-center read-toggler{% if not entry.read %} d-none{% endif %}" data-action="unread" data-message="{{ entry.message.pk }}" data-toggle="tooltip" title="Mark as unread">
            <i class="far fa-circle text-primary"></i>
          </div>
          <div class="col-3"><a href="{{ entry.message.get_absolute_url }}">{{ entry.message.author }}</a></div>
          <div class="col"><a href="{{ entry.message.get_absolute_url }}">{{ entry.message.subject }}</a></div>
          <div class="col-3"><a href="{{ entry.message.get_absolute_url }}"><span data-toggle="tooltip" title="{{ entry.date_received|date }} at {{ entry.date_received|time }}">{{ entry.date_received|naturaltime }}</span>{% if entry.message.attachments.exists %} <i class="fas fa-paperclip float-right"></i>{% endif %}</a></div>
        </div>
      </div>
    {% empty %}
      <div class="list-group-item text-center p-5">You have no messages</div>
    {% endfor %}
  </div>
{% endblock %}

project/messaging/templates/messaging/sent_items.html
{% extends "messaging/mailbox_base.htm" %}

{% load humanize %}

{% block title %}{{ block.super }}: Sent{% endblock %}

{% block message_content %}
  <div class="list-group list-group-flush mt-3">
    <div class="list-group-item list-group-item-dark">
      <div class="row" id="message-list-header">
        <div class="col-3"><strong>To</strong></div>
        <div class="col"><strong>Subject</strong></div>
        <div class="col-3"><strong>Sent</strong></div>
      </div>
    </div>
    {% for message in sent_items.all %}
      <div class="list-group-item list-group-item-action">
        <a href="{{ message.get_absolute_url }}" class="row text-decoration-none">
          <div class="col-3">{{ message.author }}</div>
          <div class="col">{{ message.subject }}</div>
          <div class="col-3"><span data-toggle="tooltip" title="{{ message.date_sent }}">{{ message.date_sent|naturaltime }}</span>{% if message.attachments.exists %} <i class="fas fa-paperclip float-right"></i>{% endif %}</div>
        </a>
      </div>
    {% empty %}
      <div class="list-group-item text-center p-5">No Messages to Display</div>
    {% endfor %}
  </div>
{% endblock %}